#!/bin/bash -e
tag_for_v1=master
tag_for_v2=2.0
if [ -e bacon.js ]; then
  cd bacon.js
  git fetch
  (cd 1.0 && git pull origin $tag_for_v1)
  (cd 2.0 && git pull origin $tag_for_v2)
else
  git clone git@github.com:baconjs/bacon.js.git
  cd bacon.js
  git worktree add ./1.0 remotes/origin/$tag_for_v1
  git worktree add ./2.0 remotes/origin/$tag_for_v2
fi
